version: 2.1

executors:
  my-executor:
    docker:
      - image: python:3.10-slim

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: venv
      - run:
          name: build and test
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
            python manage.py test
      - save_cache:
          key: venv
          paths:
            - ".venv"

workflows:
  main:
    jobs:
      - build